---
- name: Get desktop file discription
  ansible.builtin.set_fact:
    content: "{{ desktop_files[item] | default(None) }}"
  with_items: "{{ object_name }}"

- name: Create new desktop file
  ansible.builtin.template:
    src: desktop_entry.desktop.j2
    dest: /usr/share/applications/{{ object_name }}.desktop
    mode: preserve
  when: content != ""

- name: Acquiring default object properties
  ansible.builtin.set_fact:
    properties: "{{ default_launcher_object | combine(object_properties) }}"

- name: Set {{ object_name }} properties
  become_user: "{{ customize_user }}"
  become: true
  community.general.dconf:
    key: /org/mate/panel/objects/{{ object_name }}/{{ property.key }}
    value: "{{ property.value if (property.value | int) else (string_indicator + property.value + string_indicator) }}"
  loop: "{{ properties | dict2items }}"
  loop_control:
    loop_var: property

- name: Append {{ object_name }} to new panel list
  ansible.builtin.set_fact:
    new_panel_list: "{{ new_panel_list + [object_name] if object_name not in new_panel_list else new_panel_list }}"
