---
# tasks file for ubuntu-mate-desktop-customization


# -------------------------------------------
# *** Prerequisites ***
# -------------------------------------------

# - name: Updating apt-Cache
#   apt:
#     update_cache: yes
#   tags: [install, config]

# - name: Install apt packages
#   apt:
#     name: [python-psutil, dconf-editor, dbus]
#   become: yes
#   tags: [install, config]


# -------------------------------------------
# *** Theme ***
# -------------------------------------------


- name: Download GTK theme
  apt:
    name: "{{ customize_theme_package }}"
  become: yes
  when: customize_theme_package is defined
  tags: [install, config]

- name: Set GTK theme
  dconf: 
    key: "/org/mate/desktop/interface/gtk-theme" 
    value: "'{{ customize_theme_name | default('Ambiant-MATE') }}'"
  when: customize_theme_name is defined
  become_user: "{{ customize_user }}"
  tags: [config]


# -------------------------------------------
# *** Launcher ***
# -------------------------------------------

- name: Reset panel list
  dconf:
    key: "/org/mate/panel/general/object-id-list" 
    state: present
  become_user: "{{ customize_user }}"

- name: Get current panel list
  dconf: 
    key: "/org/mate/panel/general/object-id-list" 
    state: read
  register: panel_list
  become_user: "{{ customize_user }}"
  when: appendOnly
  tags: [config]

# [BUG] Is empty if never connected before ...

- name: Create and define launcher objects
  include:  create_new_panel_objects.yml 
            object_name={{ new_items.key }} 
            object_properties={{ new_items.value }}
            new_panel_list={{ panel_list.value }}
  loop: "{{ launcher_objects | dict2items }}"
  loop_control:
   loop_var: new_items

# new_panel_list="{{ default_panel_list if (panel_list.value is none) else panel_list.value }}" # Fallback if panel_list is empty or never called


- name: Set new panel list
  dconf: 
    key: "/org/mate/panel/general/object-id-list" 
    value: "{{ new_panel_list if (appendOnly and new_panel_list is defined) else override_panel_list }}"
  become_user: "{{ customize_user }}"
  tags: [config]


# -------------------------------------------
# *** Desktop Background ***
# -------------------------------------------


- name: Copy desktop-background to host
  copy: 
    src: "{{ desktop_bg_src }}" 
    dest: "/home/{{ customize_user }}/.wallpaper.jpg" 
    owner: "{{ customize_user }}" 
    group: "{{ customize_user }}" 
    mode: '777'
  tags: [config]

- name: Set desktop-background
  dconf: 
    key: "/org/mate/desktop/background/picture-filename" 
    value: "'/home/{{ customize_user }}/.wallpaper.jpg'"
  become_user: "{{ customize_user }}"
  tags: [config]
