---
# tasks file for ubuntu-mate-desktop-customization

# -------------------------------------------
# *** Prerequisites ***
# -------------------------------------------

- name: Updating apt-Cache
  apt:
    update_cache: yes
  tags: [install, config]

- name: Install apt packages
  apt:
    name: [python-psutil, dconf-editor, dbus]
  become: yes
  tags: [install, config]


# -------------------------------------------
# *** Theme ***
# -------------------------------------------


- name: Download GTK theme
  apt:
    name: "{{ customize_theme_package }}"
  become: yes
  when: customize_theme_package is defined
  tags: [install, config]

- name: Set GTK theme
  dconf: 
    key: "/org/mate/desktop/interface/gtk-theme" 
    value: "'{{ customize_theme_name | default('Ambiant-MATE') }}'"
  when: customize_theme_name is defined
  become_user: "{{ customize_user }}"
  tags: [config]


# -------------------------------------------
# *** Launcher ***
# -------------------------------------------


- name: Get current panel list
  dconf: 
    key: "/org/mate/panel/general/object-id-list" 
    state: read
  register: panel_list
  become_user: "{{ customize_user }}"
  when: appendOnly
  tags: [config]

- name: Create and define launcher objects
  include:  create_new_panel_objects.yml 
            object_name={{ item.key }} 
            object_properties={{ item.value }}
            new_panel_list={{ panel_list.value }}
  loop: "{{ launcher_objects | dict2items }}"

- name: Set new panel list
  dconf: 
    key: "/org/mate/panel/general/object-id-list" 
    value: "{{ new_panel_list if (appendOnly) else override_panel_list }}"
  become_user: "{{ customize_user }}"
  tags: [config]


# -------------------------------------------
# *** Desktop Background ***
# -------------------------------------------


- name: Copy desktop-background to host
  copy: 
    src: files/wallpaper.jpg 
    dest: "/home/{{ customize_user }}/.wallpaper.jpg" 
    owner: "{{ customize_user }}" 
    group: "{{ customize_user }}" 
    mode: '777'
  tags: [config]

- name: Set desktop-background
  dconf: 
    key: "/org/mate/desktop/background/picture-filename" 
    value: "'/home/{{ customize_user }}/.wallpaper.jpg'"
  become_user: "{{ customize_user }}"
  tags: [config]
